defaults:
  - sae: classae
  - wandb: default
  - _self_

_target_: classae.sae.config.TrainConfig

activations_path: activations/imagenet_train_L_14
epochs: 50

device: cuda
normalize_activations: true

seed: 0
shuffle_labels: false

dataloader:
  _target_: classae.sae.config.DataLoaderConfig
  num_workers: 4
  batch_size: 4096
  prefetch_factor: 2